[WIP] Initial version of TableUnspanner
everypolitician/table_unspanner pull request #1
Opened 2016-12-12 17:02 UTC by chrismytton

This is a port of the `<table>` unspanning code from https://github.com/everypolitician-scrapers/turkey-tbmm-wikipedia/pull/3.

# Notes to reviewer

The naming is currently a bit odd, the module is called `TableUnspanner` and that in turn contains a `UnspannedTable` class. I _think_ this makes sense, `TableUnspanner` is the library name, `UnspannedTable` is the object that represents a table that has been unspanned. However I am open to persuasion that this should be changed :)

2016-12-14 10:27 UTC, tmtmtmtm requested changes
As discussed on slack, I'm also a little concerned that the interface here is being driven too much by its use as a Decorator, rather than this being a good standalone library in its own right.

2016-12-14 10:27 UTC, tmtmtmtm commented on test/table_unspanner_test.rb
> +
I think you need a test that has at least one colspan, and probably at least one span in a `th` as well.

2017-01-07 10:45 UTC, tmtmtmtm commented
I'm assuming this version can be closed now?

2017-01-09 10:57 UTC, chrismytton commented
Ah yep, indeed it can!

2017-01-09 10:57 UTC, closed without merging